// Generated by Haxe 4.0.5
(function ($hx_exports, $global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
class Extension {
	static main(context) {
		Vscode.debug.registerDebugConfigurationProvider("hl",{ resolveDebugConfiguration : Extension.resolveDebugConfiguration});
	}
	static resolveDebugConfiguration(folder,config,token) {
		var config1 = config;
		if(Sys.systemName() == "Mac") {
			var visitButton = "Visit GitHub Issue";
			Vscode.window.showErrorMessage("HashLink debugging on macOS is not supported yet.",visitButton).then(function(choice) {
				if(choice == visitButton) {
					Vscode.env.openExternal(vscode_Uri.parse("https://github.com/vshaxe/hashlink-debugger/issues/28"));
				}
			});
			return null;
		}
		if(config1.type == null) {
			return null;
		}
		return new Promise(function(resolve,reject) {
			var vshaxe = Vscode.extensions.getExtension("nadako.vshaxe").exports;
			vshaxe.getActiveConfiguration().then(function(haxeConfig) {
				var _g = haxeConfig.target;
				if(_g._hx_index == 12) {
					var file = _g.file;
					if(config1.program == null) {
						config1.program = file;
					}
					var _this = haxeConfig.classPaths;
					var result = new Array(_this.length);
					var _g1 = 0;
					var _g11 = _this.length;
					while(_g1 < _g11) {
						var i = _g1++;
						result[i] = _this[i].path;
					}
					config1.classPaths = result;
					resolve(config1);
				} else {
					var e = haxeConfig.target;
					reject("Please use a Haxe configuration that targets HashLink (found target \"" + $hxEnums[e.__enum__].__constructs__[e._hx_index].toLowerCase() + "\" instead).");
				}
			},function(error) {
				reject("Unable to retrieve active Haxe configuration: " + error);
			});
		});
	}
}
$hx_exports["activate"] = Extension.main;
Extension.__name__ = true;
Math.__name__ = true;
class Sys {
	static systemName() {
		var _g = process.platform;
		switch(_g) {
		case "darwin":
			return "Mac";
		case "freebsd":
			return "BSD";
		case "linux":
			return "Linux";
		case "win32":
			return "Windows";
		default:
			var other = _g;
			return other;
		}
	}
}
Sys.__name__ = true;
class haxe_io_Output {
}
haxe_io_Output.__name__ = true;
class _$Sys_FileOutput extends haxe_io_Output {
	constructor(fd) {
		super();
		this.fd = fd;
	}
	writeByte(c) {
		js_node_Fs.writeSync(this.fd,String.fromCodePoint(c));
	}
	writeBytes(s,pos,len) {
		var data = s.b;
		return js_node_Fs.writeSync(this.fd,js_node_buffer_Buffer.from(data.buffer,data.byteOffset,s.length),pos,len);
	}
	writeString(s,encoding) {
		js_node_Fs.writeSync(this.fd,s);
	}
	flush() {
		js_node_Fs.fsyncSync(this.fd);
	}
	close() {
		js_node_Fs.closeSync(this.fd);
	}
}
_$Sys_FileOutput.__name__ = true;
class haxe_io_Input {
}
haxe_io_Input.__name__ = true;
class _$Sys_FileInput extends haxe_io_Input {
	constructor(fd) {
		super();
		this.fd = fd;
	}
	readByte() {
		var buf = js_node_buffer_Buffer.alloc(1);
		try {
			js_node_Fs.readSync(this.fd,buf,0,1,null);
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			if(e1.code == "EOF") {
				throw new js__$Boot_HaxeError(new haxe_io_Eof());
			} else {
				throw new js__$Boot_HaxeError(haxe_io_Error.Custom(e1));
			}
		}
		return buf[0];
	}
	readBytes(s,pos,len) {
		var data = s.b;
		var buf = js_node_buffer_Buffer.from(data.buffer,data.byteOffset,s.length);
		try {
			return js_node_Fs.readSync(this.fd,buf,pos,len,null);
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			if(e1.code == "EOF") {
				throw new js__$Boot_HaxeError(new haxe_io_Eof());
			} else {
				throw new js__$Boot_HaxeError(haxe_io_Error.Custom(e1));
			}
		}
	}
	close() {
		js_node_Fs.closeSync(this.fd);
	}
}
_$Sys_FileInput.__name__ = true;
var Vscode = require("vscode");
class haxe_io_Bytes {
	constructor(data) {
		this.length = data.byteLength;
		this.b = new Uint8Array(data);
		this.b.bufferValue = data;
		data.hxBytes = this;
		data.bytes = this.b;
	}
}
haxe_io_Bytes.__name__ = true;
var haxe_io_Encoding = $hxEnums["haxe.io.Encoding"] = { __ename__ : true, __constructs__ : ["UTF8","RawNative"]
	,UTF8: {_hx_index:0,__enum__:"haxe.io.Encoding",toString:$estr}
	,RawNative: {_hx_index:1,__enum__:"haxe.io.Encoding",toString:$estr}
};
class haxe_io_Eof {
	constructor() {
	}
	toString() {
		return "Eof";
	}
}
haxe_io_Eof.__name__ = true;
var haxe_io_Error = $hxEnums["haxe.io.Error"] = { __ename__ : true, __constructs__ : ["Blocked","Overflow","OutsideBounds","Custom"]
	,Blocked: {_hx_index:0,__enum__:"haxe.io.Error",toString:$estr}
	,Overflow: {_hx_index:1,__enum__:"haxe.io.Error",toString:$estr}
	,OutsideBounds: {_hx_index:2,__enum__:"haxe.io.Error",toString:$estr}
	,Custom: ($_=function(e) { return {_hx_index:3,e:e,__enum__:"haxe.io.Error",toString:$estr}; },$_.__params__ = ["e"],$_)
};
class js__$Boot_HaxeError extends Error {
	constructor(val) {
		super();
		this.val = val;
		if(Error.captureStackTrace) {
			Error.captureStackTrace(this,js__$Boot_HaxeError);
		}
	}
}
js__$Boot_HaxeError.__name__ = true;
class js_Boot {
	static __string_rec(o,s) {
		if(o == null) {
			return "null";
		}
		if(s.length >= 5) {
			return "<...>";
		}
		var t = typeof(o);
		if(t == "function" && (o.__name__ || o.__ename__)) {
			t = "object";
		}
		switch(t) {
		case "function":
			return "<function>";
		case "object":
			if(o.__enum__) {
				var e = $hxEnums[o.__enum__];
				var n = e.__constructs__[o._hx_index];
				var con = e[n];
				if(con.__params__) {
					s = s + "\t";
					return n + "(" + ((function($this) {
						var $r;
						var _g = [];
						{
							var _g1 = 0;
							var _g2 = con.__params__;
							while(true) {
								if(!(_g1 < _g2.length)) {
									break;
								}
								var p = _g2[_g1];
								_g1 = _g1 + 1;
								_g.push(js_Boot.__string_rec(o[p],s));
							}
						}
						$r = _g;
						return $r;
					}(this))).join(",") + ")";
				} else {
					return n;
				}
			}
			if(((o) instanceof Array)) {
				var str = "[";
				s += "\t";
				var _g3 = 0;
				var _g11 = o.length;
				while(_g3 < _g11) {
					var i = _g3++;
					str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
				}
				str += "]";
				return str;
			}
			var tostr;
			try {
				tostr = o.toString;
			} catch( e1 ) {
				var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
				return "???";
			}
			if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
				var s2 = o.toString();
				if(s2 != "[object Object]") {
					return s2;
				}
			}
			var str1 = "{\n";
			s += "\t";
			var hasp = o.hasOwnProperty != null;
			var k = null;
			for( k in o ) {
			if(hasp && !o.hasOwnProperty(k)) {
				continue;
			}
			if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
				continue;
			}
			if(str1.length != 2) {
				str1 += ", \n";
			}
			str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
			}
			s = s.substring(1);
			str1 += "\n" + s + "}";
			return str1;
		case "string":
			return o;
		default:
			return String(o);
		}
	}
}
js_Boot.__name__ = true;
var js_node_Fs = require("fs");
class js_node__$KeyValue_KeyValue_$Impl_$ {
	static get_key(this1) {
		return this1[0];
	}
	static get_value(this1) {
		return this1[1];
	}
}
js_node__$KeyValue_KeyValue_$Impl_$.__name__ = true;
var js_node_buffer_Buffer = require("buffer").Buffer;
class js_node_stream__$Writable_WritableNewOptionsAdapter_$Impl_$ {
	static from(options) {
		if(!Object.prototype.hasOwnProperty.call(options,"final")) {
			Object.defineProperty(options,"final",{ get : function() {
				return options.final_;
			}});
		}
		return options;
	}
}
js_node_stream__$Writable_WritableNewOptionsAdapter_$Impl_$.__name__ = true;
class js_node_url__$URLSearchParams_URLSearchParamsEntry_$Impl_$ {
	static _new(name,value) {
		var this1 = [name,value];
		return this1;
	}
	static get_name(this1) {
		return this1[0];
	}
	static get_value(this1) {
		return this1[1];
	}
}
js_node_url__$URLSearchParams_URLSearchParamsEntry_$Impl_$.__name__ = true;
var vscode_Uri = require("vscode").Uri;
var vshaxe_Target = $hxEnums["vshaxe.Target"] = { __ename__ : true, __constructs__ : ["None","Js","Lua","Swf","As3","Neko","Php","Cpp","Cppia","Cs","Java","Python","Hl","Interp"]
	,None: {_hx_index:0,__enum__:"vshaxe.Target",toString:$estr}
	,Js: ($_=function(file) { return {_hx_index:1,file:file,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["file"],$_)
	,Lua: ($_=function(file) { return {_hx_index:2,file:file,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["file"],$_)
	,Swf: ($_=function(file) { return {_hx_index:3,file:file,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["file"],$_)
	,As3: ($_=function(directory) { return {_hx_index:4,directory:directory,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["directory"],$_)
	,Neko: ($_=function(file) { return {_hx_index:5,file:file,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["file"],$_)
	,Php: ($_=function(directory) { return {_hx_index:6,directory:directory,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["directory"],$_)
	,Cpp: ($_=function(directory) { return {_hx_index:7,directory:directory,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["directory"],$_)
	,Cppia: ($_=function(file) { return {_hx_index:8,file:file,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["file"],$_)
	,Cs: ($_=function(directory) { return {_hx_index:9,directory:directory,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["directory"],$_)
	,Java: ($_=function(directory) { return {_hx_index:10,directory:directory,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["directory"],$_)
	,Python: ($_=function(file) { return {_hx_index:11,file:file,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["file"],$_)
	,Hl: ($_=function(file) { return {_hx_index:12,file:file,__enum__:"vshaxe.Target",toString:$estr}; },$_.__params__ = ["file"],$_)
	,Interp: {_hx_index:13,__enum__:"vshaxe.Target",toString:$estr}
};
var vshaxe_HaxeExecutableSource = $hxEnums["vshaxe.HaxeExecutableSource"] = { __ename__ : true, __constructs__ : ["Settings","Provider"]
	,Settings: {_hx_index:0,__enum__:"vshaxe.HaxeExecutableSource",toString:$estr}
	,Provider: ($_=function(name) { return {_hx_index:1,name:name,__enum__:"vshaxe.HaxeExecutableSource",toString:$estr}; },$_.__params__ = ["name"],$_)
};
if( String.fromCodePoint == null ) String.fromCodePoint = function(c) { return c < 0x10000 ? String.fromCharCode(c) : String.fromCharCode((c>>10)+0xD7C0)+String.fromCharCode((c&0x3FF)+0xDC00); }
String.__name__ = true;
Array.__name__ = true;
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, {});
