# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Moonshine IDE Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - uses: joshtynjala/setup-apache-flex-action@v1
      with:
        flex-version: "4.16.1"
    - name: Prepare dependencies
      working-directory: ..
      run: |
        git clone https://github.com/Moonshine-IDE/Moonshine-SDK-Installer.git
        git clone https://github.com/Moonshine-IDE/VisualEditorConverterLib.git
        git clone https://github.com/Moonshine-IDE/MockupVisualEditor.git
    - name: Build VisualEditorConverterLib with Ant
      working-directory: ../VisualEditorConverterLib
      run: ant -noinput -buildfile 'build.xml'
    - name: Build MockupVisualEditor with Ant
      working-directory: ../MockupVisualEditor
      run: ant -noinput -buildfile 'build.xml' -DMOONSHINE_LIBS_PATH=../Moonshine-IDE/ide/MoonshineDESKTOPevolved/libs
    - name: Build MoonshineDESKTOPevolved with Ant
      run: ant -noinput -buildfile 'ide\MoonshineDESKTOPevolved\build\build.xml' CompileSWFWindows
